servlet:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 30
      max: 800
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors:   always

spring:
  application:
    name: common
  profiles:
    active: de
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#?????????
#logging:
#  file:
#    path: /data/HC_logs/common/
#  level:
#    root: ERROR
#    com.shdata.health: DEBUG

mybatis-plus:
  configuration:
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.shdata.health.triage.domain
  global-config:
    db-config:
      id-type: INPUT
    banner: true
